### ISSUE TITLE
"This is an example." is not a fun fact

### ISSUE THREAD

**Issue by jonahweissman** [chssigma/cool-repo#1]
I have a bug to report. In several markdown files, the following table appears:

> Name | Username | Fun Fact
> --- | --- | ---
> Jack Timmins | [Tim-Jackins](https://github.com/TIm-Jackins) | This is an example.

However, it contains an inaccuracy! "This is an example" may indeed be a fact, but it is certainly not fun. Please fix.

**Comment by Tim-Jackins** [comment]
Fun Facts have been [added](https://github.com/chssigma/cool-repo/commit/4659d1df45caabf435580b37128014001cce2fbd)
